# Generated by Django 4.2.28 on 2026-08-03 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_gradescale_grade_point'),
        ('notifications', '0003_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_groups', to='academic.class'),
        ),
    ]
