# Generated by Django 4.2.28 on 2026-08-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_groupmessage_is_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('notice', 'Notice'), ('circular', 'Circular'), ('event', 'Event')], default='notice', max_length=20),
        ),
    ]
