# Generated by Codex on 2026-05-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_studentsubjectscore"),
        ("quizzes", "0002_question_explanation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalQuizAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("time_limit_minutes", models.PositiveIntegerField(default=10)),
                ("score", models.FloatField(default=0)),
                ("total_points", models.FloatField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("is_submitted", models.BooleanField(default=False)),
                ("class_group", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="personal_quiz_attempts", to="academic.class")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="personal_quiz_attempts", to=settings.AUTH_USER_MODEL)),
                ("subject", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="personal_quiz_attempts", to="academic.subject")),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="personal_quiz_attempts", to="tenants.tenant")),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="PersonalQuizQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_type", models.CharField(choices=[("objective", "Objective"), ("true_false", "True or False"), ("fill_blank", "Fill in the blank")], max_length=20)),
                ("prompt", models.TextField()),
                ("options", models.JSONField(blank=True, default=list)),
                ("correct_answer", models.CharField(max_length=255)),
                ("explanation", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("points", models.PositiveIntegerField(default=1)),
                ("attempt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="quizzes.personalquizattempt")),
            ],
            options={"ordering": ["order", "id"]},
        ),
        migrations.CreateModel(
            name="PersonalQuizAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answer_text", models.CharField(blank=True, max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                ("earned_points", models.FloatField(default=0)),
                ("attempt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="quizzes.personalquizattempt")),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="quizzes.personalquizquestion")),
            ],
            options={"unique_together": {("attempt", "question")}},
        ),
    ]
