# Generated by Codex on 2026-05-16

from django.db import migrations, models
import django.db.models.deletion


def backfill_personal_quiz_metrics(apps, schema_editor):
    PersonalQuizAttempt = apps.get_model("quizzes", "PersonalQuizAttempt")
    Term = apps.get_model("academic", "Term")
    AcademicYear = apps.get_model("academic", "AcademicYear")

    terms = list(Term.objects.select_related("academic_year").order_by("start_date"))
    years = list(AcademicYear.objects.order_by("start_date"))

    for attempt in PersonalQuizAttempt.objects.all().iterator():
        basis_date = attempt.daily_date
        if basis_date is None:
            source_dt = attempt.submitted_at or attempt.started_at
            if source_dt:
                basis_date = source_dt.date()
        if basis_date is None:
            continue

        attempt.week_start = basis_date - __import__("datetime").timedelta(days=basis_date.weekday())
        attempt.month_start = basis_date.replace(day=1)
        if attempt.total_points:
            attempt.percentage = round((float(attempt.score or 0) / max(float(attempt.total_points or 0), 1.0)) * 100, 2)

        if not attempt.term_id:
            term = next((item for item in terms if item.start_date <= basis_date <= item.end_date), None)
            if term:
                attempt.term_id = term.id
                if getattr(term, "academic_year_id", None):
                    attempt.academic_year_id = term.academic_year_id
        if not attempt.academic_year_id:
            year = next((item for item in years if item.start_date <= basis_date <= item.end_date), None)
            if year:
                attempt.academic_year_id = year.id

        attempt.save(update_fields=["week_start", "month_start", "percentage", "term", "academic_year"])


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0008_studentsubjectscore_approved_at"),
        ("quizzes", "0006_personal_quiz_global_subject_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalquizattempt",
            name="academic_year",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="personal_quiz_attempts", to="academic.academicyear"),
        ),
        migrations.AddField(
            model_name="personalquizattempt",
            name="term",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="personal_quiz_attempts", to="academic.term"),
        ),
        migrations.AddField(
            model_name="personalquizattempt",
            name="percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="personalquizattempt",
            name="week_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalquizattempt",
            name="month_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_personal_quiz_metrics, migrations.RunPython.noop),
    ]
