from django.urls import path

from . import app_views

urlpatterns = [
    path("dashboard/", app_views.dashboard_snapshot, name="app_dashboard_snapshot"),
    path("student/dashboard/", app_views.student_dashboard, name="app_student_dashboard"),
    path("teacher/dashboard/", app_views.teacher_dashboard, name="app_teacher_dashboard"),
    path("school/settings/", app_views.school_settings, name="app_school_settings"),
    path("database-imports/", app_views.database_imports, name="app_database_imports"),
    path("academic/planning/", app_views.lesson_planning, name="app_lesson_planning"),
    path("academic/notes/", app_views.teacher_notes, name="app_teacher_notes"),
    path("students/", app_views.students_snapshot, name="app_students_snapshot"),
    path("students/create/", app_views.create_student, name="app_create_student"),
    path("students/<uuid:student_id>/", app_views.student_detail, name="app_student_detail"),
    path("documents/", app_views.documents_snapshot, name="app_documents_snapshot"),
    path("documents/transcripts/<uuid:student_id>/", app_views.transcript_detail, name="app_transcript_detail"),
    path("documents/testimonials/<uuid:student_id>/", app_views.testimonial_detail, name="app_testimonial_detail"),
    path("teachers/", app_views.teachers_snapshot, name="app_teachers_snapshot"),
    path("teachers/create/", app_views.create_teacher, name="app_create_teacher"),
    path("teachers/<uuid:teacher_id>/", app_views.teacher_detail, name="app_teacher_detail"),
    path("id-cards/", app_views.id_cards_snapshot, name="app_id_cards_snapshot"),
    path("id-cards/qr/", app_views.id_card_qr_code, name="app_id_card_qr_code"),
    path("id-cards/verify/", app_views.id_card_verify, name="app_id_card_verify"),
    path("enrollments/", app_views.enrollments_snapshot, name="app_enrollments_snapshot"),
    path("enrollments/create/", app_views.create_enrollment, name="app_create_enrollment"),
    path("classes/", app_views.classes_snapshot, name="app_classes_snapshot"),
    path("classes/create/", app_views.create_class, name="app_create_class"),
    path("classes/<int:class_id>/", app_views.class_detail, name="app_class_detail"),
    path("subjects/create/", app_views.create_subject, name="app_create_subject"),
    path("subjects/<int:subject_id>/", app_views.subject_detail, name="app_subject_detail"),
    path("exams/", app_views.exams_snapshot, name="app_exams_snapshot"),
    path("exams/question-bank/", app_views.cbt_question_bank, name="app_cbt_question_bank"),
    path("exams/create/", app_views.create_exam, name="app_create_exam"),
    path("exams/<int:exam_id>/", app_views.exam_detail, name="app_exam_detail"),
    path("exams/<int:exam_id>/results/upload/", app_views.upload_exam_results, name="app_upload_exam_results"),
    path("exams/<int:exam_id>/notify/", app_views.notify_exam_update, name="app_notify_exam_update"),
    path("messages/", app_views.messages_snapshot, name="app_messages_snapshot"),
    path("messages/inbox/", app_views.messages_inbox, name="app_messages_inbox"),
    path("messages/send/", app_views.send_message, name="app_send_message"),
    path("messages/<uuid:message_id>/read/", app_views.mark_message_read, name="app_mark_message_read"),
    path("messages/<uuid:message_id>/", app_views.delete_message, name="app_delete_message"),
    path("notifications/<uuid:notification_id>/read/", app_views.mark_notification_read, name="app_mark_notification_read"),
    path("attendance/mark/", app_views.mark_attendance, name="app_mark_attendance"),
    path("attendance/class-students/", app_views.teacher_class_students, name="app_teacher_class_students"),
    path("attendance/teacher-mark/", app_views.teacher_mark_student_attendance, name="app_teacher_mark_attendance"),
    path("questions/create/", app_views.create_question_prompt, name="app_create_question_prompt"),
    path("questions/answer/", app_views.answer_question_prompt, name="app_answer_question_prompt"),
    path("results/", app_views.results_snapshot, name="app_results_snapshot"),
    path("results/grades/", app_views.grading_scales, name="app_grading_scales"),
    path("results/my/", app_views.student_my_results, name="app_student_my_results"),
    path("results/submit/", app_views.submit_subject_score, name="app_submit_subject_score"),
    path("results/push/", app_views.push_results_to_admin, name="app_push_results"),
    path("results/batches/<int:batch_id>/review/", app_views.review_result_batch, name="app_review_result_batch"),
    path("results/batches/<int:batch_id>/", app_views.delete_result_batch, name="app_delete_result_batch"),
    path("results/report/<str:student_code>/", app_views.student_report_card, name="app_student_report_card"),
]
