# Generated by Django 4.2.28 on 2026-05-07

import decimal
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_auditlog_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("staff_code", models.CharField(max_length=40)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("staff_type", models.CharField(choices=[("teaching", "Teaching"), ("non_teaching", "Non-teaching")], default="teaching", max_length=20)),
                ("role", models.CharField(max_length=120)),
                ("department", models.CharField(blank=True, max_length=120)),
                ("employment_type", models.CharField(default="full_time", max_length=30)),
                ("employment_status", models.CharField(choices=[("active", "Active"), ("on_leave", "On leave"), ("suspended", "Suspended"), ("exited", "Exited")], default="active", max_length=20)),
                ("hire_date", models.DateField(default=django.utils.timezone.localdate)),
                ("base_salary", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("salary_balance", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("bank_account_name", models.CharField(blank=True, max_length=150)),
                ("bank_account_number", models.CharField(blank=True, max_length=30)),
                ("emergency_contact_name", models.CharField(blank=True, max_length=150)),
                ("emergency_contact_phone", models.CharField(blank=True, max_length=30)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_staff_profiles", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="staff_profiles", to="core.schooltenant")),
                ("user", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="hr_staff_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="StaffActivity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=80)),
                ("details", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="staff_activity_actions", to=settings.AUTH_USER_MODEL)),
                ("staff", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="activities", to="hr.staffprofile")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="staff_activities", to="core.schooltenant")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("status", models.CharField(choices=[("present", "Present"), ("absent", "Absent"), ("late", "Late"), ("half_day", "Half day")], default="present", max_length=20)),
                ("check_in", models.TimeField(blank=True, null=True)),
                ("check_out", models.TimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("marked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="marked_staff_attendance", to=settings.AUTH_USER_MODEL)),
                ("staff", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to="hr.staffprofile")),
            ],
            options={
                "ordering": ["-date", "staff__first_name"],
            },
        ),
        migrations.CreateModel(
            name="SalaryAdvanceRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("paid", "Paid")], default="pending", max_length=20)),
                ("request_date", models.DateField(default=django.utils.timezone.localdate)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_salary_advances", to=settings.AUTH_USER_MODEL)),
                ("staff", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="salary_advances", to="hr.staffprofile")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("allowances", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("deductions", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("advances_applied", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("gross_salary", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("net_salary", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("amount_paid", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("balance_after_payment", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("approved", "Approved"), ("paid", "Paid")], default="draft", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processed_payroll_records", to=settings.AUTH_USER_MODEL)),
                ("staff", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payroll_records", to="hr.staffprofile")),
            ],
            options={
                "ordering": ["-year", "-month", "staff__first_name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("leave_type", models.CharField(default="Annual", max_length=60)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("admin_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_staff_leaves", to=settings.AUTH_USER_MODEL)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_staff_leaves", to=settings.AUTH_USER_MODEL)),
                ("staff", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leave_requests", to="hr.staffprofile")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(model_name="staffprofile", index=models.Index(fields=["tenant", "staff_type"], name="hr_staffpro_tenant__6fb9e8_idx")),
        migrations.AddIndex(model_name="staffprofile", index=models.Index(fields=["tenant", "department"], name="hr_staffpro_tenant__88d00d_idx")),
        migrations.AddIndex(model_name="staffprofile", index=models.Index(fields=["employment_status"], name="hr_staffpro_employm_589508_idx")),
        migrations.AddConstraint(model_name="staffprofile", constraint=models.UniqueConstraint(fields=("tenant", "staff_code"), name="unique_staff_code_per_school")),
        migrations.AddIndex(model_name="staffactivity", index=models.Index(fields=["tenant", "created_at"], name="hr_staffact_tenant__0492ce_idx")),
        migrations.AddIndex(model_name="staffattendance", index=models.Index(fields=["date", "status"], name="hr_staffatt_date_3e1475_idx")),
        migrations.AddConstraint(model_name="staffattendance", constraint=models.UniqueConstraint(fields=("staff", "date"), name="unique_staff_attendance_per_day")),
        migrations.AddIndex(model_name="salaryadvancerequest", index=models.Index(fields=["status", "request_date"], name="hr_salaryad_status_86489c_idx")),
        migrations.AddIndex(model_name="payrollrecord", index=models.Index(fields=["year", "month", "status"], name="hr_payrollr_year_7b0749_idx")),
        migrations.AddConstraint(model_name="payrollrecord", constraint=models.UniqueConstraint(fields=("staff", "year", "month"), name="unique_staff_payroll_month")),
        migrations.AddIndex(model_name="leaverequest", index=models.Index(fields=["status", "start_date"], name="hr_leavere_status_8d0e3b_idx")),
    ]
