# Generated by Django 4.2.28 on 2026-05-07

import secrets
from django.db import migrations, models


def backfill_attendance_tokens(apps, schema_editor):
    StaffProfile = apps.get_model("hr", "StaffProfile")
    for staff in StaffProfile.objects.filter(attendance_token=""):
        staff.attendance_token = secrets.token_urlsafe(48)
        staff.save(update_fields=["attendance_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="attendance_token",
            field=models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True),
        ),
        migrations.RunPython(backfill_attendance_tokens, migrations.RunPython.noop),
    ]
