# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_staffprofile_attendance_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="staff/documents/"),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="emergency_contact_relation",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
