# Generated by Django 4.2.28 on 2026-08-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_staffprofile_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half day'), ('excused', 'Excused')], default='present', max_length=20),
        ),
    ]
