# Generated by Django 4.2.28 on 2026-08-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_staffattendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='staff/signatures/'),
        ),
    ]
