# Generated by Django 6.0.8 on 2026-09-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_staffprofile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
