# Generated by Django 4.2.28 on 2026-06-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_collections', '0003_schoolcollectionprofile_flutterwave_customer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='collectionauditlog',
            new_name='fee_collect_school__1c4cc8_idx',
            old_name='fee_collect_school__f37025_idx',
        ),
        migrations.RenameIndex(
            model_name='collectionauditlog',
            new_name='fee_collect_action_848152_idx',
            old_name='fee_collect_action_2d3a18_idx',
        ),
        migrations.RenameIndex(
            model_name='collectionauditlog',
            new_name='fee_collect_referen_387c49_idx',
            old_name='fee_collect_referen_e208b6_idx',
        ),
        migrations.RenameIndex(
            model_name='feepayment',
            new_name='fee_collect_school__280c13_idx',
            old_name='fee_collect_school__01a13f_idx',
        ),
        migrations.RenameIndex(
            model_name='feepayment',
            new_name='fee_collect_provide_b4b87d_idx',
            old_name='fee_collect_provide_162ce7_idx',
        ),
        migrations.RenameIndex(
            model_name='feepayment',
            new_name='fee_collect_session_074013_idx',
            old_name='fee_collect_session_2c3d97_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolcollectionprofile',
            new_name='fee_collect_school__f3ccec_idx',
            old_name='fee_collect_school__9f2f6b_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolcollectionprofile',
            new_name='fee_collect_status_666135_idx',
            old_name='fee_collect_status_28d9ff_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolsettlement',
            new_name='fee_collect_school__5e448b_idx',
            old_name='fee_collect_school__8b7110_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolsettlement',
            new_name='fee_collect_schedul_28bc72_idx',
            old_name='fee_collect_schedul_854bf1_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolsettlement',
            new_name='fee_collect_transfe_ba5322_idx',
            old_name='fee_collect_transfe_2f0ccd_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolvirtualaccount',
            new_name='fee_collect_account_4973e2_idx',
            old_name='fee_collect_account_0337e2_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolvirtualaccount',
            new_name='fee_collect_provide_91e3ea_idx',
            old_name='fee_collect_provide_948c7d_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolvirtualaccount',
            new_name='fee_collect_school__917523_idx',
            old_name='fee_collect_school__ff4e07_idx',
        ),
    ]
