# Generated by Django 4.2.28 on 2026-02-27 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('secondary_color', models.CharField(default='#1E40AF', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('font_family', models.CharField(default='Segoe UI', max_length=100)),
                ('is_dark_mode_enabled', models.BooleanField(default=False)),
                ('school_tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='core.schooltenant')),
            ],
            options={
                'verbose_name': 'Theme Configuration',
                'verbose_name_plural': 'Theme Configurations',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('offline_exams', 'Offline Exams'), ('analytics', 'Analytics'), ('assignments', 'Assignments'), ('discussion_forum', 'Discussion Forum'), ('video_conferencing', 'Video Conferencing'), ('advance_payments', 'Advance Payments')], max_length=50)),
                ('is_enabled', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('school_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.schooltenant')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'unique_together': {('school_tenant', 'code')},
            },
        ),
    ]
