# Generated by Django 4.2.28 on 2026-08-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_schooltenant_welcome_email_sent_at'),
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('id_card_orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='landscape', max_length=10)),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('letter', 'Letter')], default='A4', max_length=10)),
                ('margin_mm', models.PositiveSmallIntegerField(default=15)),
                ('font_family', models.CharField(default='Segoe UI', max_length=100)),
                ('font_size_body', models.PositiveSmallIntegerField(default=13)),
                ('font_size_heading', models.PositiveSmallIntegerField(default=20)),
                ('primary_color', models.CharField(default='#0f766e', max_length=7)),
                ('secondary_color', models.CharField(default='#0f172a', max_length=7)),
                ('accent_color', models.CharField(default='#0f766e', max_length=7)),
                ('table_style', models.CharField(choices=[('bordered', 'Bordered'), ('striped', 'Striped'), ('minimal', 'Minimal')], default='bordered', max_length=10)),
                ('border_style', models.CharField(choices=[('solid', 'Solid'), ('double', 'Double'), ('dashed', 'Dashed'), ('none', 'None')], default='solid', max_length=10)),
                ('border_width', models.PositiveSmallIntegerField(default=1)),
                ('header_note', models.CharField(blank=True, default='', max_length=255)),
                ('footer_text', models.TextField(blank=True, default='')),
                ('show_logo', models.BooleanField(default=True)),
                ('show_signature', models.BooleanField(default=True)),
                ('watermark_enabled', models.BooleanField(default=False)),
                ('watermark_source', models.CharField(choices=[('text', 'Text'), ('logo', 'School logo')], default='text', max_length=10)),
                ('watermark_text', models.CharField(blank=True, default='', max_length=60)),
                ('watermark_opacity', models.PositiveSmallIntegerField(default=8)),
                ('school_tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_theme', to='core.schooltenant')),
            ],
            options={
                'verbose_name': 'Document Theme',
                'verbose_name_plural': 'Document Themes',
            },
        ),
    ]
