# Generated by Django 4.2.28 on 2026-08-25 22:21

import device_fleet.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_schooltenant_welcome_email_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('unregistered', 'Unregistered'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('maintenance', 'Maintenance')], default='unregistered', max_length=15)),
                ('authorized', models.BooleanField(default=False)),
                ('auth_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, default='', max_length=20)),
                ('device_model', models.CharField(blank=True, default='', max_length=120)),
                ('os_version', models.CharField(blank=True, default='', max_length=60)),
                ('battery_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('battery_charging', models.BooleanField(blank=True, null=True)),
                ('battery_health', models.CharField(blank=True, choices=[('good', 'Good'), ('normal', 'Normal'), ('fair', 'Fair'), ('poor', 'Poor'), ('unknown', 'Unknown'), ('not_supported', 'Not Supported')], default='', max_length=15)),
                ('battery_temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('first_activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_registered', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_revoked', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanner_devices', to='core.schooltenant')),
            ],
            options={
                'verbose_name': 'Scanner Device',
                'verbose_name_plural': 'Scanner Devices',
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='ProvisioningKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(default=device_fleet.models.generate_provisioning_key, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('used', 'Used'), ('revoked', 'Revoked')], default='unused', max_length=10)),
                ('single_use', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioning_keys_created', to=settings.AUTH_USER_MODEL)),
                ('used_by_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioning_keys_used', to='device_fleet.device')),
            ],
            options={
                'verbose_name': 'Provisioning Key',
                'verbose_name_plural': 'Provisioning Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=60)),
                ('details', models.TextField(blank=True, default='')),
                ('result', models.CharField(default='success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='device_fleet.device')),
            ],
            options={
                'verbose_name': 'Device Audit Log',
                'verbose_name_plural': 'Device Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='device_flee_device__5f4bcd_idx')],
            },
        ),
    ]
