# Generated by Django 4.2.28 on 2026-08-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='license_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
