# Generated by Django 4.2.28 on 2026-08-25 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device_fleet', '0002_device_license_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='scanner_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanner_device', to=settings.AUTH_USER_MODEL),
        ),
    ]
