# Generated by Django 6.0.8 on 2026-10-09 07:29

import django.db.models.deletion
import mail_inbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_label', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('account_label', 'uid'), name='unique_account_uid')],
            },
        ),
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=mail_inbox.models.attachment_upload_to)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail_inbox.inboundmessage')),
            ],
        ),
    ]
