# Generated by Django 4.2.28 on 2026-07-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exampin_plain_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_format',
            field=models.CharField(choices=[('objective', 'Objective (MCQ)'), ('theory', 'Theory'), ('mixed', 'Mixed (Objective + Theory)')], default='objective', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='question_attachments/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('paragraph', 'Paragraph'), ('essay', 'Essay')], max_length=20),
        ),
    ]
