# Generated by Django 4.2.28 on 2026-08-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_exam_format_question_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='last_autosaved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
