# Generated by Django 4.2.28 on 2026-08-26 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('academic', '0019_attendancerecord_card_uid_idempotency_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0011_seed_global_question_bank_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('timing_mode', models.CharField(choices=[('general', 'One duration for all subjects'), ('per_subject', 'Individual duration per subject')], default='general', max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('instructions', models.TextField(blank=True)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='exampin',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='exampinusage',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_usage_events', to='exams.exam'),
        ),
        # NOTE: reordered from the auto-generated output - AddIndex/AddConstraint
        # for the new `group` fields must come after those fields actually exist
        # (AddField below), not before. Django's autodetector emitted them in the
        # wrong order (index/constraint operations before the AddField that
        # creates the field they reference), which fails with
        # "ExamPin has no field named 'group'" on a fresh apply.
        migrations.AddField(
            model_name='examgroup',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
        migrations.AddField(
            model_name='examgroup',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examgroup',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_exams', to='exams.examgroup'),
        ),
        migrations.AddField(
            model_name='exampin',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='exams.examgroup'),
        ),
        migrations.AddField(
            model_name='exampinusage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_usage_events', to='exams.examgroup'),
        ),
        migrations.AddIndex(
            model_name='exampin',
            index=models.Index(fields=['group', 'is_active', 'expires_at'], name='exams_examp_group_i_520bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='exampinusage',
            index=models.Index(fields=['group', 'status', 'created_at'], name='exams_examp_group_i_4cc0ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='exampin',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('exam__isnull', False), ('group__isnull', True)), models.Q(('exam__isnull', True), ('group__isnull', False)), _connector='OR'), name='exampin_requires_exam_xor_group'),
        ),
        migrations.AddConstraint(
            model_name='exampinusage',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('exam__isnull', False), ('group__isnull', True)), models.Q(('exam__isnull', True), ('group__isnull', False)), _connector='OR'), name='exampinusage_requires_exam_xor_group'),
        ),
    ]
