# Generated by Django 4.2.28 on 2026-09-03 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_attendancerecord_academic_year_attendancerecord_term'),
        ('exams', '0012_examgroup_alter_exampin_exam_alter_exampinusage_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='academic.term'),
        ),
    ]
