# Generated by Django 4.2.28 on 2026-05-02 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=100)),
                ('initial_credits', models.IntegerField(default=100)),
                ('purchased_credits', models.IntegerField(default=0)),
                ('used_credits', models.IntegerField(default=0)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_credits', to='core.schooltenant')),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('purchase', 'Credit Purchase'), ('deduction', 'Student Registration Deduction'), ('adjustment', 'Manual Adjustment'), ('refund', 'Refund')], max_length=32)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=64, null=True)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.admincredit')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_credit', 'tx_type'], name='finance_cre_admin_c_6bf0a7_idx'), models.Index(fields=['status'], name='finance_cre_status_28dffc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='admincredit',
            index=models.Index(fields=['tenant'], name='finance_adm_tenant__626fd4_idx'),
        ),
        migrations.AddConstraint(
            model_name='admincredit',
            constraint=models.UniqueConstraint(fields=('tenant',), name='unique_admin_credit_per_tenant'),
        ),
    ]
