# Generated by Codex on 2026-05-06

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_studentsubjectscore"),
        ("finance", "0003_remove_admin_credits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassFee",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=150)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="NGN", max_length=5)),
                ("due_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_class_fees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="academic.class",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
                "unique_together": {("school_class", "title", "due_date")},
            },
        ),
        migrations.AddField(
            model_name="schoolfee",
            name="class_fee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_fees",
                to="finance.classfee",
            ),
        ),
        migrations.AddIndex(
            model_name="classfee",
            index=models.Index(fields=["school_class", "is_active"], name="finance_cla_school__9ccfd5_idx"),
        ),
    ]
