# Generated by Codex on 2026-05-07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auditlog_user_and_more"),
        ("finance", "0004_classfee_schoolfee_class_fee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0004_teacherprofile_subjects_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivationCreditPool",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("balance", models.PositiveIntegerField(default=0)),
                ("price_per_credit", models.DecimalField(decimal_places=2, default=Decimal("200.00"), max_digits=10)),
                ("currency", models.CharField(default="NGN", max_length=5)),
                ("auto_assign_enabled", models.BooleanField(default=False)),
                ("auto_assign_scope", models.CharField(default="all", max_length=20)),
                ("last_auto_assigned_month", models.CharField(blank=True, max_length=7)),
                ("last_reminder_month", models.CharField(blank=True, max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation_credit_pool",
                        to="core.schooltenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentActivationCredit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("credits_assigned", models.PositiveIntegerField(default=0)),
                ("active_until", models.DateField(blank=True, null=True)),
                ("last_credit_assigned_at", models.DateTimeField(blank=True, null=True)),
                ("inactive_since", models.DateField(blank=True, null=True)),
                ("inactive_flagged_at", models.DateTimeField(blank=True, null=True)),
                ("is_excluded_from_auto_deductions", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation_credit",
                        to="users.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivationCreditTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tx_type", models.CharField(choices=[("purchase", "Credit Purchase"), ("assignment", "Manual Assignment"), ("auto_assignment", "Auto Assignment"), ("adjustment", "Adjustment")], max_length=32)),
                ("credits", models.IntegerField()),
                ("price_per_credit", models.DecimalField(decimal_places=2, default=Decimal("200.00"), max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("narration", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activation_credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finance.activationcreditpool",
                    ),
                ),
                (
                    "student_credit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.studentactivationcredit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="studentactivationcredit",
            index=models.Index(fields=["active_until"], name="finance_stu_active__483bba_idx"),
        ),
        migrations.AddIndex(
            model_name="studentactivationcredit",
            index=models.Index(fields=["is_excluded_from_auto_deductions"], name="finance_stu_is_excl_afd21d_idx"),
        ),
        migrations.AddIndex(
            model_name="activationcredittransaction",
            index=models.Index(fields=["pool", "tx_type"], name="finance_act_pool_id_853068_idx"),
        ),
        migrations.AddIndex(
            model_name="activationcredittransaction",
            index=models.Index(fields=["created_at"], name="finance_act_created_1c761d_idx"),
        ),
    ]
