# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_activation_credit_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationcredittransaction",
            name="provider",
            field=models.CharField(default="flutterwave", max_length=30),
        ),
        migrations.AddField(
            model_name="activationcredittransaction",
            name="status",
            field=models.CharField(choices=[("pending", "Pending"), ("successful", "Successful"), ("failed", "Failed")], default="successful", max_length=16),
        ),
    ]
