# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_activationcredittransaction_provider_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="provider",
            field=models.CharField(default="flutterwave", max_length=30),
        ),
    ]
