# Generated by Django 4.2.28 on 2026-05-10 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_admin_otp_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0008_smart_payment_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGenerationCreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('transcript', 'Transcript'), ('testimonial', 'Testimonial'), ('id_card', 'ID Card')], max_length=20)),
                ('credits_deducted', models.PositiveIntegerField(default=1)),
                ('action', models.CharField(blank=True, help_text='generate, download, print, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='bankpayment',
            new_name='finance_ban_tenant__03ef03_idx',
            old_name='finance_ban_tenant__ce1f3c_idx',
        ),
        migrations.RenameIndex(
            model_name='bankpayment',
            new_name='finance_ban_student_4b577c_idx',
            old_name='finance_ban_student_fde675_idx',
        ),
        migrations.RenameIndex(
            model_name='bankpayment',
            new_name='finance_ban_bank_re_51f308_idx',
            old_name='finance_ban_bank_re_7f5b52_idx',
        ),
        migrations.RenameIndex(
            model_name='studentpaymentreference',
            new_name='finance_stu_tenant__02a408_idx',
            old_name='finance_stu_tenant__5e24fb_idx',
        ),
        migrations.RenameIndex(
            model_name='studentpaymentreference',
            new_name='finance_stu_student_84bfe8_idx',
            old_name='finance_stu_student_9c4f3a_idx',
        ),
        migrations.AddField(
            model_name='documentgenerationcredittransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_credit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentgenerationcredittransaction',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_credit_transactions', to='finance.activationcreditpool'),
        ),
        migrations.AddField(
            model_name='documentgenerationcredittransaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_generation_credits', to='users.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='documentgenerationcredittransaction',
            index=models.Index(fields=['pool', 'document_type'], name='finance_doc_pool_id_0fd37e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentgenerationcredittransaction',
            index=models.Index(fields=['created_at'], name='finance_doc_created_e6e057_idx'),
        ),
    ]
