# Generated by Django 4.2.28 on 2026-05-11 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0009_add_document_generation_credit_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('vendor', models.CharField(blank=True, max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('record_type', models.CharField(choices=[('expense', 'Expense'), ('bill', 'Bill'), ('receipt', 'Receipt')], default='expense', max_length=16)),
                ('category', models.CharField(default='Operations', max_length=80)),
                ('color', models.CharField(default='#14b8a6', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('due', 'Due'), ('paid', 'Paid')], default='pending', max_length=16)),
                ('record_date', models.DateField()),
                ('receipt_number', models.CharField(blank=True, max_length=80)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expense_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_records', to='core.schooltenant')),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'record_type'], name='finance_exp_tenant__fd52c6_idx'), models.Index(fields=['tenant', 'status'], name='finance_exp_tenant__0df1c6_idx'), models.Index(fields=['record_date'], name='finance_exp_record__95b8dc_idx')],
            },
        ),
    ]
