# Generated by Codex on 2026-05-13

from django.db import migrations, models
from django.db.models import Count


def dedupe_student_document_charges(apps, schema_editor):
    DocumentGenerationCreditTransaction = apps.get_model("finance", "DocumentGenerationCreditTransaction")
    duplicate_groups = (
        DocumentGenerationCreditTransaction.objects
        .exclude(student__isnull=True)
        .values("pool_id", "student_id", "document_type")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for group in duplicate_groups:
        records = list(
            DocumentGenerationCreditTransaction.objects
            .filter(
                pool_id=group["pool_id"],
                student_id=group["student_id"],
                document_type=group["document_type"],
            )
            .order_by("created_at", "id")
            .values_list("id", flat=True)
        )
        if len(records) > 1:
            DocumentGenerationCreditTransaction.objects.filter(id__in=records[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_expenserecord"),
    ]

    operations = [
        migrations.RunPython(dedupe_student_document_charges, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="documentgenerationcredittransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(student__isnull=False),
                fields=["pool", "student", "document_type"],
                name="unique_student_document_generation_charge",
            ),
        ),
    ]
