# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_unique_student_document_generation_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenserecord",
            name="phone_number",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
