# Generated by Codex on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_expenserecord_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolfee",
            name="is_customized",
            field=models.BooleanField(default=False),
        ),
    ]
