# Generated by Django 4.2.28 on 2026-06-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_financeledgerlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='financeledgerlog',
            new_name='finance_fin_tenant__731435_idx',
            old_name='finance_fin_tenant__52c38a_idx',
        ),
        migrations.RenameIndex(
            model_name='financeledgerlog',
            new_name='finance_fin_action_28f140_idx',
            old_name='finance_fin_action_d8eb4f_idx',
        ),
        migrations.RenameIndex(
            model_name='financeledgerlog',
            new_name='finance_fin_referen_48f365_idx',
            old_name='finance_fin_referen_23fa6b_idx',
        ),
    ]
