# Generated by Django 4.2.28 on 2026-06-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_adminwallet_kuda_virtual_account'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banklink',
            new_name='finance_ban_bank_na_c515f7_idx',
            old_name='finance_ban_bank_na_3ce2a8_idx',
        ),
    ]
