# Generated by Django 4.2.28 on 2026-06-23 11:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_rename_finance_ban_bank_na_3ce2a8_idx_finance_ban_bank_na_c515f7_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_allocated', models.DecimalField(decimal_places=2, help_text='Tuition amount allocated to this fee', max_digits=14)),
                ('paystack_fee_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('schooldom_fee_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('pending', 'Pending')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adminwallet',
            name='split_code',
            field=models.CharField(blank=True, help_text='Paystack split code for this school', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminwallet',
            name='subaccount_code',
            field=models.CharField(blank=True, help_text='Paystack subaccount code for this school', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schoolfee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='schoolfee',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolfee',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolfee',
            name='paystack_ref',
            field=models.CharField(blank=True, help_text='Paystack reference for last payment', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='allocation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('partial', 'Partial'), ('overpaid', 'Overpaid')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of fee IDs allocated'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parent_id',
            field=models.UUIDField(blank=True, help_text='Parent user ID for this transaction', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paystack_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Paystack processing fee', max_digits=14),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paystack_ref',
            field=models.CharField(blank=True, help_text='Paystack transaction reference', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='school_id',
            field=models.UUIDField(blank=True, help_text='School tenant ID for this transaction', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='schooldom_markup',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Schooldom service fee', max_digits=14),
        ),
        migrations.AddField(
            model_name='transaction',
            name='split_code',
            field=models.CharField(blank=True, help_text='Paystack split code used', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tuition_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tuition amount', max_digits=14),
        ),
        migrations.AlterField(
            model_name='schoolfee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('partial', 'Partial')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('fund', 'Funding'), ('fee_debit', 'Fee Debit'), ('fee_credit', 'Fee Credit'), ('withdrawal', 'Withdrawal'), ('adjustment_credit', 'Adjustment Credit'), ('adjustment_debit', 'Adjustment Debit'), ('split_payment', 'Split Payment'), ('school_settlement', 'School Settlement'), ('schooldom_fee', 'Schooldom Fee'), ('paystack_fee', 'Paystack Fee')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='schoolfee',
            index=models.Index(fields=['paystack_ref'], name='finance_sch_paystac_6ee4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['paystack_ref'], name='finance_tra_paystac_a6178b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['allocation_status'], name='finance_tra_allocat_9698f5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['parent_id'], name='finance_tra_parent__9079d4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['school_id'], name='finance_tra_school__92c62a_idx'),
        ),
        migrations.AddField(
            model_name='feeallocation',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.schoolfee'),
        ),
        migrations.AddField(
            model_name='feeallocation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.transaction'),
        ),
        migrations.AddIndex(
            model_name='feeallocation',
            index=models.Index(fields=['fee', 'status'], name='finance_fee_fee_id_de21e2_idx'),
        ),
        migrations.AddIndex(
            model_name='feeallocation',
            index=models.Index(fields=['transaction'], name='finance_fee_transac_99a007_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feeallocation',
            unique_together={('fee', 'transaction')},
        ),
    ]
