# Generated by Django 4.2.28 on 2026-06-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_parentvirtualaccount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parentvirtualaccount',
            new_name='finance_par_account_148ae4_idx',
            old_name='finance_par_acct_num_idx',
        ),
        migrations.RenameIndex(
            model_name='parentvirtualaccount',
            new_name='finance_par_tenant__5be3df_idx',
            old_name='finance_par_tenant_idx',
        ),
    ]
