# Generated by Django 4.2.28 on 2026-06-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_rename_finance_par_acct_num_idx_finance_par_account_148ae4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwallet',
            name='dva_split_code',
            field=models.CharField(blank=True, help_text="Paystack percentage split code applied to this school's dedicated virtual accounts", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminwallet',
            name='split_code',
            field=models.CharField(blank=True, help_text='Paystack split code for this school (flat, used at checkout)', max_length=50, null=True),
        ),
    ]
