# Generated by Django 4.2.28 on 2026-07-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_paymentreceiptlink'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentreceiptlink',
            new_name='finance_pay_token_da7feb_idx',
            old_name='finance_pay_token_idx',
        ),
    ]
