# Generated by Django 4.2.28 on 2026-07-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_sms_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessagelog',
            name='category',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('fee_reminder', 'Fee Reminder'), ('results', 'Results'), ('otp', 'OTP'), ('parent_alert', 'Parent Alert'), ('teacher_notice', 'Teacher Notice'), ('bulk', 'Bulk Message'), ('receipt', 'Payment Receipt'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
