# Generated by Django 4.2.28 on 2026-07-25 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_schooltenant_ops_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0028_alter_smsmessagelog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('expires_at', models.DateField(blank=True, help_text='Leave blank for an allocation that never expires.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text="Set automatically once the daily expiry job has deducted this allocation's credits from the pool.", null=True)),
                ('notified_7d_at', models.DateTimeField(blank=True, null=True)),
                ('notified_1d_at', models.DateTimeField(blank=True, null=True)),
                ('notified_expired_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_allocations_created', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.activationcreditpool')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_allocations', to='core.schooltenant')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['tenant', 'expires_at'], name='finance_tok_tenant__212ced_idx')],
            },
        ),
    ]
