# Generated by Django 4.2.28 on 2026-07-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_staffprofile_extended_fields'),
        ('finance', '0029_tokenallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='payroll_record',
            field=models.OneToOneField(blank=True, help_text='For record_type=payslip - the payroll transaction this row was generated from. OneToOne so a given staff/month payroll can never produce more than one Payslip row here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_record', to='hr.payrollrecord'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='record_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('bill', 'Bill'), ('receipt', 'Receipt'), ('payslip', 'Payslip')], default='expense', max_length=16),
        ),
    ]
