# Generated by Django 4.2.28 on 2026-07-31 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('finance', '0030_expenserecord_payroll_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='inventory_item',
            field=models.OneToOneField(blank=True, help_text='For record_type=inventory_purchase - the inventory item this row was generated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_record', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='record_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('bill', 'Bill'), ('receipt', 'Receipt'), ('payslip', 'Payslip'), ('inventory_purchase', 'Inventory Purchase')], default='expense', max_length=24),
        ),
    ]
