# Generated by Django 4.2.28 on 2026-08-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_bill_schoolfee_invoice_number_schoolfee_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='accent_color',
            field=models.CharField(default='#0f766e', help_text="Hex color applied to the invoice's headers, borders, and highlights.", max_length=7),
        ),
    ]
