# Generated by Django 4.2.28 on 2026-08-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_bankpayment_receipt_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smswallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='successful', max_length=16),
        ),
    ]
