# Generated by Django 4.2.28 on 2026-07-31 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_schooltenant_welcome_email_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventory_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='Other', max_length=80)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('model_number', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('supplier', models.CharField(blank=True, max_length=160)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reorder_level', models.PositiveIntegerField(default=1)),
                ('unit_of_measurement', models.CharField(default='unit', max_length=40)),
                ('warranty_period_months', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_lifespan_years', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=160)),
                ('assigned_department', models.CharField(blank=True, max_length=120)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('under_repair', 'Under Repair'), ('lost', 'Lost'), ('disposed', 'Disposed')], default='new', max_length=20)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('notified_low_stock_at', models.DateTimeField(blank=True, null=True)),
                ('notified_warranty_expiring_at', models.DateTimeField(blank=True, null=True)),
                ('notified_warranty_expired_at', models.DateTimeField(blank=True, null=True)),
                ('notified_maintenance_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.schooltenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItemImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='inventory/items/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='inventory.inventoryitem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_audit_logs', to='core.schooltenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('add', 'Stock Added'), ('remove', 'Stock Removed'), ('transfer', 'Transferred'), ('issue', 'Issued'), ('return', 'Returned'), ('dispose', 'Disposed')], max_length=20)),
                ('quantity_change', models.IntegerField(default=0)),
                ('resulting_quantity', models.PositiveIntegerField()),
                ('from_location', models.CharField(blank=True, max_length=160)),
                ('to_location', models.CharField(blank=True, max_length=160)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.inventoryitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock_movements', to='core.schooltenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', 'created_at'], name='inventory_s_item_id_a9fe64_idx'), models.Index(fields=['tenant', 'movement_type', 'created_at'], name='inventory_s_tenant__130e8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_assigned', models.PositiveIntegerField(default=1)),
                ('borrower_label', models.CharField(blank=True, max_length=160)),
                ('date_issued', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('condition_before', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('under_repair', 'Under Repair'), ('lost', 'Lost'), ('disposed', 'Disposed')], default='good', max_length=20)),
                ('condition_after', models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('under_repair', 'Under Repair'), ('lost', 'Lost'), ('disposed', 'Disposed')], max_length=20)),
                ('status', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost')], default='borrowed', max_length=20)),
                ('notified_overdue_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('borrower_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_borrowings', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.inventoryitem')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_assignments', to='core.schooltenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'expected_return_date'], name='inventory_i_tenant__c7b4f2_idx'), models.Index(fields=['item', 'status'], name='inventory_i_item_id_e64111_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant', 'is_archived', 'created_at'], name='inventory_i_tenant__f39884_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant', 'category'], name='inventory_i_tenant__b993d5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant', 'condition'], name='inventory_i_tenant__2e2e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryauditlog',
            index=models.Index(fields=['tenant', 'created_at'], name='inventory_i_tenant__164fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryauditlog',
            index=models.Index(fields=['item', 'created_at'], name='inventory_i_item_id_7d46b7_idx'),
        ),
    ]
