# Generated by Django 4.2.28 on 2026-05-04 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auditlog_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Secure token embedded in QR code', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qr_codes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(help_text='School tenant this QR code belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_qr_code', to='core.schooltenant')),
            ],
            options={
                'verbose_name': 'Attendance QR Code',
                'verbose_name_plural': 'Attendance QR Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(auto_now_add=True)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('qr_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.attendanceqrcode')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendances', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance', to='core.schooltenant')),
            ],
            options={
                'verbose_name': 'Teacher Attendance',
                'verbose_name_plural': 'Teacher Attendances',
                'ordering': ['-attendance_date', '-check_in_time'],
                'indexes': [models.Index(fields=['teacher', 'attendance_date'], name='attendance__teacher_ff6fe1_idx'), models.Index(fields=['tenant', 'attendance_date'], name='attendance__tenant__7ed4fe_idx'), models.Index(fields=['check_in_time'], name='attendance__check_i_c4b353_idx')],
                'unique_together': {('teacher', 'attendance_date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('late_days', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='core.schooltenant')),
            ],
            options={
                'verbose_name': 'Attendance Report',
                'verbose_name_plural': 'Attendance Reports',
                'ordering': ['-period_start'],
                'unique_together': {('teacher', 'period_start', 'period_end')},
            },
        ),
    ]
