# Generated by Django 4.2.28 on 2026-02-12 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('email', 'Email'), ('url', 'URL'), ('color', 'Color'), ('file', 'File')], default='string', max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('system', 'System'), ('security', 'Security'), ('email', 'Email'), ('sms', 'SMS'), ('payment', 'Payment'), ('storage', 'Storage'), ('api', 'API'), ('features', 'Features'), ('maintenance', 'Maintenance')], default='system', max_length=20)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category'], name='app_setting_categor_78d155_idx'), models.Index(fields=['key'], name='app_setting_key_f3d5b8_idx')],
            },
        ),
    ]
