# Generated by Django 4.2.28 on 2026-03-06 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('core', '0004_auditlog_user_and_more'),
        ('exams', '0001_initial'),
        ('academic', '0002_term'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('welcome_subject', models.CharField(default='Enrollment update', max_length=200)),
                ('welcome_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrollments', to='academic.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL)),
                ('enrollment_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_records', to='notifications.inappmessage')),
                ('exams', models.ManyToManyField(blank=True, related_name='student_enrollments', to='exams.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='core.schooltenant')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'student enrollment',
                'verbose_name_plural': 'student enrollments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'student'], name='users_stude_school__5b13b4_idx'), models.Index(fields=['created_at'], name='users_stude_created_31e7cd_idx')],
            },
        ),
    ]
