# Generated by Django 4.2.28 on 2026-03-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_studentsubjectscore'),
        ('users', '0002_studentenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='academic.subject'),
        ),
    ]
