# Generated by Django 4.2.28 on 2026-03-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacherprofile_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
