# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_teacherprofile_subjects_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="local_government",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="state_of_origin",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
