# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_studentprofile_local_government_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="disability",
            field=models.CharField(blank=True, default="no", max_length=20),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="home_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="student_type",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
