# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_studentsubjectscore"),
        ("users", "0006_studentprofile_disability_home_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="assigned_classes",
            field=models.ManyToManyField(blank=True, related_name="assigned_teachers", to="academic.class"),
        ),
    ]
