# Generated by Django 4.2.28 on 2026-05-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_teacherprofile_assigned_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('school_admin', 'School Administrator'), ('principal', 'Principal'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=20),
        ),
    ]
