# Generated by Django 4.2.28 on 2026-05-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_admin_otp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
