# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_rename_databaseimportjob_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Administrator"),
                    ("school_admin", "School Administrator"),
                    ("principal", "Principal"),
                    ("accountant", "Accountant"),
                    ("teacher", "Teacher"),
                    ("staff", "Staff"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
