# Generated by Codex on 2026-06-01

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auditlog_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0015_add_accountant_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical_issue", "Technical Issue"),
                            ("account_issue", "Account Issue"),
                            ("billing_issue", "Billing Issue"),
                            ("feature_request", "Feature Request"),
                            ("general_inquiry", "General Inquiry"),
                        ],
                        max_length=40,
                    ),
                ),
                ("subject", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("attachment", models.FileField(blank=True, null=True, upload_to="support_tickets/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("awaiting_response", "Awaiting Response"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=24,
                    ),
                ),
                ("requester_email", models.EmailField(blank=True, max_length=254)),
                ("support_notified_at", models.DateTimeField(blank=True, null=True)),
                ("requester_notified_at", models.DateTimeField(blank=True, null=True)),
                ("last_status_email_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="support_tickets", to="core.schooltenant")),
                ("submitted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="support_tickets", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["school", "status"], name="users_suppo_school__5acb79_idx"),
                    models.Index(fields=["school", "created_at"], name="users_suppo_school__4e71c8_idx"),
                ],
            },
        ),
    ]
