# Generated by Django 4.2.28 on 2026-06-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_supportticket'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='users_suppo_school__d62898_idx',
            old_name='users_suppo_school__5acb79_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='users_suppo_school__e09f1e_idx',
            old_name='users_suppo_school__4e71c8_idx',
        ),
    ]
