# Generated by Django 4.2.28 on 2026-06-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_schoolgroup_schooltenant_school_group'),
        ('users', '0022_studentprofile_id_card_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.schoolgroup'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('school_superadmin', 'School Superadmin'), ('school_admin', 'School Administrator'), ('principal', 'Principal'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=20),
        ),
    ]
