# Generated by Django 4.2.28 on 2026-07-06 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_schoolgroup_schooltenant_school_group'),
        ('users', '0023_user_school_group_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purpose', models.CharField(max_length=255)),
                ('repayment_period_months', models.PositiveIntegerField()),
                ('additional_notes', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='loan_applications/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=24)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('requester_phone', models.CharField(blank=True, max_length=32)),
                ('support_notified_at', models.DateTimeField(blank=True, null=True)),
                ('requester_notified_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_email_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='core.schooltenant')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='users_loana_school__b4b1cd_idx'), models.Index(fields=['school', 'created_at'], name='users_loana_school__577bf3_idx')],
            },
        ),
    ]
