# Generated by Django 4.2.28 on 2026-07-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_loanapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='director_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='director_id_document',
            field=models.FileField(blank=True, null=True, upload_to='directors/id_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='director_id_type',
            field=models.CharField(blank=True, choices=[('drivers_license', "Driver's License"), ('nin', 'National ID (NIN)'), ('voters_card', "Voter's Card"), ('passport', 'International Passport')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='director_proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to='directors/proof_of_address/%Y/%m/'),
        ),
    ]
