# Generated by Django 4.2.28 on 2026-07-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_kidsmonitorsubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kidsmonitorsubscription',
            new_name='users_kidsm_school__c49958_idx',
            old_name='users_kidsm_school__is_ac_idx',
        ),
    ]
