# Generated by Django 4.2.28 on 2026-07-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_kidsmonitorsubscription_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='director_signature',
            field=models.ImageField(blank=True, null=True, upload_to='directors/signatures/%Y/%m/'),
        ),
    ]
