# Generated by Django 4.2.28 on 2026-07-24 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_schooltenant_ops_region'),
        ('users', '0030_user_director_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_date', models.DateField()),
                ('school_legal_name', models.CharField(max_length=255)),
                ('school_registered_address', models.TextField()),
                ('representative_name', models.CharField(max_length=255)),
                ('representative_title', models.CharField(max_length=255)),
                ('notice_days', models.PositiveIntegerField(default=14)),
                ('cure_period_days', models.PositiveIntegerField(default=14)),
                ('negotiation_days', models.PositiveIntegerField(default=30)),
                ('signature', models.ImageField(upload_to='service_agreements/signatures/%Y/%m/')),
                ('document', models.FileField(blank=True, null=True, upload_to='service_agreements/%Y/%m/')),
                ('support_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_agreements', to='core.schooltenant')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'created_at'], name='users_servi_school__b3591c_idx')],
            },
        ),
    ]
