# Generated by Django 4.2.28 on 2026-09-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0024_lessonplan_attachment'),
        ('users', '0031_serviceagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='elective_subjects',
            field=models.ManyToManyField(blank=True, related_name='elective_students', to='academic.subject'),
        ),
    ]
