# Generated by Django 6.0.8 on 2026-09-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_studentprofile_elective_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='middle name'),
        ),
    ]
