# Generated by Django 4.2.28 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_studentsubjectscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="subjects",
            field=models.ManyToManyField(blank=True, related_name="classes", to="academic.subject"),
        ),
    ]
