# Generated by Django 4.2.28 on 2026-05-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0006_academicyear_teachernote_term_academic_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeScale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("letter", models.CharField(max_length=5)),
                ("min_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("remark", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant")),
            ],
            options={
                "ordering": ["-min_percentage", "letter"],
                "unique_together": {("tenant", "letter")},
            },
        ),
        migrations.CreateModel(
            name="ResultBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("pending", "Pending admin review"), ("approved", "Approved"), ("published", "Published"), ("rejected", "Rejected")], default="draft", max_length=20)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("class_group", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="result_batches", to="academic.class")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_result_batches", to=settings.AUTH_USER_MODEL)),
                ("teacher", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="result_batches", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant")),
                ("term", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="result_batches", to="academic.term")),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(model_name="studentsubjectscore", name="assessment_score", field=models.DecimalField(decimal_places=2, default=0, max_digits=6)),
        migrations.AddField(model_name="studentsubjectscore", name="assignment_score", field=models.DecimalField(decimal_places=2, default=0, max_digits=6)),
        migrations.AddField(model_name="studentsubjectscore", name="attendance_score", field=models.DecimalField(decimal_places=2, default=0, max_digits=6)),
        migrations.AddField(model_name="studentsubjectscore", name="cbt_score", field=models.DecimalField(decimal_places=2, default=0, max_digits=6)),
        migrations.AddField(model_name="studentsubjectscore", name="grade", field=models.CharField(blank=True, max_length=5)),
        migrations.AddField(model_name="studentsubjectscore", name="other_score", field=models.DecimalField(decimal_places=2, default=0, max_digits=6)),
        migrations.AddField(model_name="studentsubjectscore", name="performance_remark", field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name="studentsubjectscore", name="published_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="studentsubjectscore", name="submitted_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="studentsubjectscore", name="theory_score", field=models.DecimalField(decimal_places=2, default=0, max_digits=6)),
        migrations.AddField(
            model_name="studentsubjectscore",
            name="approval_status",
            field=models.CharField(choices=[("draft", "Draft"), ("pending", "Pending admin review"), ("approved", "Approved"), ("published", "Published"), ("rejected", "Rejected")], default="draft", max_length=20),
        ),
        migrations.AddField(
            model_name="studentsubjectscore",
            name="approved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_subject_scores", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="studentsubjectscore",
            name="result_batch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="scores", to="academic.resultbatch"),
        ),
    ]
