# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0007_gradescale_resultbatch_scores_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubjectscore",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
