# Generated by Django 4.2.28 on 2026-06-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_schoolactivitycalendar'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='schoolactivitycalendar',
            new_name='academic_sc_tenant__820de7_idx',
            old_name='academic_sc_tenant__a2e0b8_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolactivitycalendar',
            new_name='academic_sc_tenant__103a01_idx',
            old_name='academic_sc_tenant__af6e7b_idx',
        ),
    ]
