# Generated by Django 4.2.28 on 2026-07-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_timetableentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='academic.subject'),
        ),
    ]
