# Generated by Django 4.2.28 on 2026-07-24 15:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_timetableentry_title_alter_timetableentry_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradescale',
            name='grade_point',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3),
        ),
    ]
