# Generated by Django 4.2.28 on 2026-08-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_attendancerecord_clock_in_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10),
        ),
    ]
