# Generated by Django 4.2.28 on 2026-08-21 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('academic', '0017_attendancerecord_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassResultSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('class_size', models.PositiveIntegerField(default=0)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_snapshots', to='academic.class')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_class_result_snapshots', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_snapshots', to='academic.term')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('tenant', 'class_group', 'term')},
            },
        ),
    ]
