# Generated by Django 4.2.28 (hand-written to match makemigrations' output format -
# no working Python/venv was available in this environment to run it directly).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0018_classresultsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='card_uid',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
