# Generated by Django 4.2.28 on 2026-08-28 10:15

import academic.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('academic', '0019_attendancerecord_card_uid_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periods_per_day', models.PositiveSmallIntegerField(default=8)),
                ('period_duration_minutes', models.PositiveSmallIntegerField(default=40)),
                ('day_start_time', models.TimeField(default=datetime.time(8, 0))),
                ('school_days', models.JSONField(blank=True, default=academic.models._default_school_days)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='academic_ti_tenant__b0d209_idx')],
            },
        ),
    ]
