# Generated by Django 4.2.28 on 2026-09-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_timetablesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesettings',
            name='break_periods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
