# Generated by Django 4.2.28 on 2026-09-03 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_timetablesettings_break_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='academic.term'),
        ),
    ]
