# Generated by Django 4.2.28 on 2026-09-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0023_termtransitionstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='lesson_plans/%Y/%m/'),
        ),
    ]
