# Generated by Django 6.0.8 on 2026-10-06 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0024_lessonplan_attachment'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('grade_level', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('objectives', models.TextField(blank=True, default='')),
                ('activities', models.TextField(blank=True, default='')),
                ('resources', models.TextField(blank=True, default='')),
                ('assessment', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lesson_resources/%Y/%m/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_resources', to='academic.subject')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['subject__name', 'title'],
            },
        ),
    ]
