# Generated by Django 4.2.28 on 2026-02-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '__first__'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Domain', 'verbose_name_plural': 'Domains'},
        ),
        migrations.AddField(
            model_name='domain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='enabled_features',
            field=models.ManyToManyField(blank=True, related_name='schools', to='settings_app.featureflag'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
