# Generated by Django 4.2.28 on 2026-06-12 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_schooltenant_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_school_groups', to=settings.AUTH_USER_MODEL, db_constraint=False)),
            ],
            options={
                'verbose_name': 'School Group',
                'verbose_name_plural': 'School Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='school_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='core.schoolgroup'),
        ),
    ]
