# Generated by Django 4.2.28 on 2026-07-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_schoolgroup_schooltenant_school_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltenant',
            name='cac_certificate',
            field=models.FileField(blank=True, null=True, upload_to='school_compliance/cac_certificates/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='cac_registered_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='entrance_photo',
            field=models.ImageField(blank=True, null=True, upload_to='school_compliance/entrance_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='ministry_approval_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to='school_compliance/proof_of_address/%Y/%m/'),
        ),
    ]
