# Generated by Django 4.2.28 on 2026-07-06 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_schooltenant_cac_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltenant',
            name='compliance_deadline_reference_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='compliance_reminder_stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='compliance_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='compliance_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='compliance_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted - Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='compliance_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='compliance_suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schooltenant',
            name='signup_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
