# Generated by Django 4.2.28 on 2026-07-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
        ('core', '0011_schooltenant_country_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltenant',
            name='ops_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='ops.region'),
        ),
    ]
