# Generated by Django 4.2.28 on 2026-07-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_schooltenant_ops_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltenant',
            name='welcome_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
