# Generated by Django 4.2.28 on 2026-09-05 22:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0023_termtransitionstate_and_more'),
        ('core', '0013_schooltenant_welcome_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltenant',
            name='product',
            field=models.CharField(choices=[('full', 'Full SchoolDom'), ('schoolgate', 'SchoolGate')], default='full', max_length=20),
        ),
        migrations.CreateModel(
            name='SchoolGatePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('device', 'Device Fee'), ('termly', 'Termly Subscription')], max_length=10)),
                ('plan', models.CharField(blank=True, default='', max_length=20)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('per_student_price', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolgate_payments', to='core.schooltenant')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.term')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'payment_type', 'status'], name='core_school_tenant__dea40b_idx')],
            },
        ),
    ]
