# Generated by Django 6.0.8 on 2026-09-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_schooltenant_product_schoolgatepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltenant',
            name='grading_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
