# Generated by Django 4.2.28 on 2026-07-30 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import request_queue.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_schooltenant_welcome_email_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('retrying', 'Retrying'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('dedupe_key', models.CharField(db_index=True, max_length=64)),
                ('is_archived', models.BooleanField(default=False)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=5)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=request_queue.models.default_expiry)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='request_queue.queuedrequest')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queued_requests', to='core.schooltenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueuedRequestEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('processing_started', 'Processing started'), ('retry_scheduled', 'Retry scheduled'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('duplicate_detected', 'Duplicate detected'), ('archived', 'Archived'), ('manual_retry', 'Manual retry')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_request_events', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='request_queue.queuedrequest')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['request', 'created_at'], name='request_que_request_f85eae_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='queuedrequest',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='request_que_tenant__35e902_idx'),
        ),
        migrations.AddIndex(
            model_name='queuedrequest',
            index=models.Index(fields=['request_type', 'status'], name='request_que_request_f5290c_idx'),
        ),
        migrations.AddIndex(
            model_name='queuedrequest',
            index=models.Index(fields=['dedupe_key'], name='request_que_dedupe__6df7e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='queuedrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'queued', 'processing', 'retrying'])), fields=('dedupe_key',), name='unique_active_dedupe_key'),
        ),
    ]
