# Generated by Django 4.2.28 (hand-written to match makemigrations' output format -
# no working Python/venv was available in this environment to run it directly).

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_schooltenant_welcome_email_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_uid', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_assignments_revoked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='card_assignments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_assignments', to='core.schooltenant')),
            ],
            options={
                'verbose_name': 'Card Assignment',
                'verbose_name_plural': 'Card Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cardassignment',
            index=models.Index(fields=['tenant', 'status'], name='rfid_attend_tenant__d3f1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='cardassignment',
            index=models.Index(fields=['card_uid'], name='rfid_attend_card_ui_7c9e4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cardassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tenant', 'card_uid'), name='unique_active_card_uid_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='cardassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student',), name='unique_active_card_per_student'),
        ),
    ]
