# Generated by Django 4.2.28 (hand-written to match makemigrations' output format -
# no working Python/venv was available in this environment to run it directly).
#
# A proper follow-up migration, not an edit to 0001_initial - the VPS already ran
# migrate with the old `student` column before this change was made, so rewriting
# history here would leave production with a stale student_id column that no
# longer matches models.py.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfid_attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cardassignment',
            name='unique_active_card_per_student',
        ),
        migrations.RenameField(
            model_name='cardassignment',
            old_name='student',
            new_name='holder',
        ),
        migrations.AlterField(
            model_name='cardassignment',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cardassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('holder',), name='unique_active_card_per_holder'),
        ),
    ]
