# Generated by Django 4.2.28 on 2026-09-05 22:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_schooltenant_product_schoolgatepayment'),
        ('rfid_attendance', '0002_rename_student_to_holder'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('attendance_only', 'Attendance Only'), ('fee_tracker', 'Fee Tracker')], default='attendance_only', max_length=20)),
                ('early_start', models.TimeField(default=datetime.time(7, 30))),
                ('early_end', models.TimeField(default=datetime.time(8, 30))),
                ('late_start', models.TimeField(default=datetime.time(8, 31))),
                ('late_end', models.TimeField(default=datetime.time(10, 0))),
                ('clockout_start', models.TimeField(default=datetime.time(13, 0))),
                ('clockout_end', models.TimeField(default=datetime.time(16, 0))),
                ('duplicate_protection_seconds', models.PositiveIntegerField(default=30)),
                ('admin_pin_hash', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gate_settings', to='core.schooltenant')),
            ],
            options={
                'verbose_name': 'Gate Settings',
                'verbose_name_plural': 'Gate Settings',
            },
        ),
    ]
