# Generated by Django 4.2.28 on 2026-07-22 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ceo', 'CEO'), ('cto', 'CTO'), ('cfo', 'CFO'), ('growth_manager', 'Growth Manager'), ('senior_marketer', 'Senior Marketer'), ('marketer', 'Marketer')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', 'region__name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ceo', 'CEO'), ('cto', 'CTO'), ('cfo', 'CFO'), ('growth_manager', 'Growth Manager'), ('senior_marketer', 'Senior Marketer'), ('marketer', 'Marketer')], max_length=20)),
                ('module', models.CharField(choices=[('school_onboarding', 'School onboarding'), ('compliance_verification', 'Compliance verification'), ('token_assignment', 'Token assignment'), ('churn_dashboard', 'Churn & adoption dashboard'), ('revenue_features', 'Revenue features'), ('lead_pipeline', 'Lead pipeline'), ('training_tools', 'School training tools'), ('students_staff_data', 'Students & staff data'), ('team_performance', 'Team performance & reporting'), ('team_management', 'Team management'), ('team_management_scoped', 'Team management (own region only)'), ('slack_controls', 'Slack channel controls'), ('billing_plan', 'Billing & plan')], max_length=40)),
                ('granted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['module', 'role'],
                'unique_together': {('role', 'module')},
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('role_default_changed', 'Role default changed'), ('member_override_set', 'Member override set'), ('member_override_cleared', 'Member override cleared')], max_length=30)),
                ('role', models.CharField(blank=True, choices=[('ceo', 'CEO'), ('cto', 'CTO'), ('cfo', 'CFO'), ('growth_manager', 'Growth Manager'), ('senior_marketer', 'Senior Marketer'), ('marketer', 'Marketer')], max_length=20)),
                ('module', models.CharField(choices=[('school_onboarding', 'School onboarding'), ('compliance_verification', 'Compliance verification'), ('token_assignment', 'Token assignment'), ('churn_dashboard', 'Churn & adoption dashboard'), ('revenue_features', 'Revenue features'), ('lead_pipeline', 'Lead pipeline'), ('training_tools', 'School training tools'), ('students_staff_data', 'Students & staff data'), ('team_performance', 'Team performance & reporting'), ('team_management', 'Team management'), ('team_management_scoped', 'Team management (own region only)'), ('slack_controls', 'Slack channel controls'), ('billing_plan', 'Billing & plan')], max_length=40)),
                ('old_value', models.BooleanField(null=True)),
                ('new_value', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_permission_changes_made', to=settings.AUTH_USER_MODEL)),
                ('target_ops_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_change_log', to='ops.opsuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='opsuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ops_users', to='ops.region'),
        ),
        migrations.AddField(
            model_name='opsuser',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='ops.opsuser'),
        ),
        migrations.AddField(
            model_name='opsuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ops_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MemberPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('school_onboarding', 'School onboarding'), ('compliance_verification', 'Compliance verification'), ('token_assignment', 'Token assignment'), ('churn_dashboard', 'Churn & adoption dashboard'), ('revenue_features', 'Revenue features'), ('lead_pipeline', 'Lead pipeline'), ('training_tools', 'School training tools'), ('students_staff_data', 'Students & staff data'), ('team_performance', 'Team performance & reporting'), ('team_management', 'Team management'), ('team_management_scoped', 'Team management (own region only)'), ('slack_controls', 'Slack channel controls'), ('billing_plan', 'Billing & plan')], max_length=40)),
                ('granted', models.BooleanField()),
                ('ops_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='ops.opsuser')),
            ],
            options={
                'unique_together': {('ops_user', 'module')},
            },
        ),
    ]
