# Generated by Django 4.2.28 on 2026-07-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_seed_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
