# Generated by Django 6.0.8 on 2026-10-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_alter_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpermission',
            name='module',
            field=models.CharField(choices=[('school_onboarding', 'School onboarding'), ('compliance_verification', 'Compliance verification'), ('token_assignment', 'Token assignment'), ('churn_dashboard', 'Churn & adoption dashboard'), ('revenue_features', 'Revenue features'), ('lead_pipeline', 'Lead pipeline'), ('training_tools', 'School training tools'), ('students_staff_data', 'Students & staff data'), ('team_performance', 'Team performance & reporting'), ('team_management', 'Team management'), ('team_management_scoped', 'Team management (own region only)'), ('slack_controls', 'Slack channel controls'), ('billing_plan', 'Billing & plan'), ('support_mail', 'Support mail inbox')], max_length=40),
        ),
        migrations.AlterField(
            model_name='permissionauditlog',
            name='module',
            field=models.CharField(choices=[('school_onboarding', 'School onboarding'), ('compliance_verification', 'Compliance verification'), ('token_assignment', 'Token assignment'), ('churn_dashboard', 'Churn & adoption dashboard'), ('revenue_features', 'Revenue features'), ('lead_pipeline', 'Lead pipeline'), ('training_tools', 'School training tools'), ('students_staff_data', 'Students & staff data'), ('team_performance', 'Team performance & reporting'), ('team_management', 'Team management'), ('team_management_scoped', 'Team management (own region only)'), ('slack_controls', 'Slack channel controls'), ('billing_plan', 'Billing & plan'), ('support_mail', 'Support mail inbox')], max_length=40),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('school_onboarding', 'School onboarding'), ('compliance_verification', 'Compliance verification'), ('token_assignment', 'Token assignment'), ('churn_dashboard', 'Churn & adoption dashboard'), ('revenue_features', 'Revenue features'), ('lead_pipeline', 'Lead pipeline'), ('training_tools', 'School training tools'), ('students_staff_data', 'Students & staff data'), ('team_performance', 'Team performance & reporting'), ('team_management', 'Team management'), ('team_management_scoped', 'Team management (own region only)'), ('slack_controls', 'Slack channel controls'), ('billing_plan', 'Billing & plan'), ('support_mail', 'Support mail inbox')], max_length=40),
        ),
    ]
